-- Data: a trial gives the bar a new game each week, which they can run as
-- often as they like, one game at a time (Curt's call), instead of one
-- night a week. Rewords the seeded checklists, step descriptions and
-- follow-up titles with targeted text replacements, so any other edits
-- are kept. Follow-ups already created are unchanged.
UPDATE "PipelineStage" SET
  "playbookLocal" = replace(replace(replace(replace(replace(replace(replace(replace(replace("playbookLocal", 'free, one night a week', 'free, with a new game each week to run as often as they like'), 'free, every night if they want', 'free, with a new game each week to run as often as they like'), 'up to {{trialWeeks}} weeks, one night a week', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'up to {{trialWeeks}} weeks, as many nights as they like', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'Agree on the champion, the trial night,', 'Agree on the champion, which nights they''ll run it,'), 'Agree the trial night, today''s headcount', 'Agree which nights they''ll run it, today''s headcount'), 'the staff member who starts the game each week', 'the staff member who starts the game each time they run it'), 'the staff member who starts the game each night they run it', 'the staff member who starts the game each time they run it'), 'Confirm the trial night and champion', 'Confirm the trial nights and champion'),
  "playbookRemote" = replace(replace(replace(replace(replace(replace(replace(replace(replace("playbookRemote", 'free, one night a week', 'free, with a new game each week to run as often as they like'), 'free, every night if they want', 'free, with a new game each week to run as often as they like'), 'up to {{trialWeeks}} weeks, one night a week', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'up to {{trialWeeks}} weeks, as many nights as they like', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'Agree on the champion, the trial night,', 'Agree on the champion, which nights they''ll run it,'), 'Agree the trial night, today''s headcount', 'Agree which nights they''ll run it, today''s headcount'), 'the staff member who starts the game each week', 'the staff member who starts the game each time they run it'), 'the staff member who starts the game each night they run it', 'the staff member who starts the game each time they run it'), 'Confirm the trial night and champion', 'Confirm the trial nights and champion'),
  "description" = replace(replace(replace(replace(replace(replace(replace(replace(replace("description", 'free, one night a week', 'free, with a new game each week to run as often as they like'), 'free, every night if they want', 'free, with a new game each week to run as often as they like'), 'up to {{trialWeeks}} weeks, one night a week', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'up to {{trialWeeks}} weeks, as many nights as they like', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'Agree on the champion, the trial night,', 'Agree on the champion, which nights they''ll run it,'), 'Agree the trial night, today''s headcount', 'Agree which nights they''ll run it, today''s headcount'), 'the staff member who starts the game each week', 'the staff member who starts the game each time they run it'), 'the staff member who starts the game each night they run it', 'the staff member who starts the game each time they run it'), 'Confirm the trial night and champion', 'Confirm the trial nights and champion');

UPDATE "PipelineStageTask" SET "title" = replace(replace(replace(replace(replace(replace(replace(replace(replace("title", 'free, one night a week', 'free, with a new game each week to run as often as they like'), 'free, every night if they want', 'free, with a new game each week to run as often as they like'), 'up to {{trialWeeks}} weeks, one night a week', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'up to {{trialWeeks}} weeks, as many nights as they like', 'up to {{trialWeeks}} weeks, with a new game each week that they can run as often as they like (one game at a time)'), 'Agree on the champion, the trial night,', 'Agree on the champion, which nights they''ll run it,'), 'Agree the trial night, today''s headcount', 'Agree which nights they''ll run it, today''s headcount'), 'the staff member who starts the game each week', 'the staff member who starts the game each time they run it'), 'the staff member who starts the game each night they run it', 'the staff member who starts the game each time they run it'), 'Confirm the trial night and champion', 'Confirm the trial nights and champion');
